modLoader="javafml"
loaderVersion="[47,)"
license="GPL-2.0"

[[mods]]
    modId="wizards_reborn"
    version="${file.jarVersion}"
    updateJSONURL = "https://raw.githubusercontent.com/MaxBogomol/WizardsReborn/refs/heads/master/update.json"
    displayName="Wizard's Reborn"
    logoFile="wizards_reborn.png"
    authors="MaxBogomol"
    description="Adds magical things"

[[dependencies.wizards_reborn]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.wizards_reborn]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.wizards_reborn]]
    modId = "fluffy_fur"
    mandatory = true
    versionRange = "[1.20.1-0.1.5,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.wizards_reborn]]
    modId = "curios"
    mandatory = true
    versionRange = "[5.2.0-beta.3+1.20.1,)"
    ordering = "AFTER"
    side = "BOTH"